# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Virtual.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_VirtualAssistance(object):
    def setupUi(self, VirtualAssistance):
        VirtualAssistance.setObjectName("VirtualAssistance")
        VirtualAssistance.resize(1198, 678)
        self.centralwidget = QtWidgets.QWidget(VirtualAssistance)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -30, 1211, 741))
        font = QtGui.QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(36)
        self.label.setFont(font)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:/Users/SAKSHI/Desktop/final year project/image/ui1.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(1070, 490, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(13)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 170, 0);\n"
"font: 87 13pt \"Segoe UI Black\";")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(1070, 530, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 0, 0);\n"
"border-color: rgb(0, 170, 0);\n"
"font: 87 11pt \"Segoe UI Black\";")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 10, 111, 61))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../../../Users/SAKSHI/Desktop/final year project/image/p.png"))
        self.label_2.setScaledContents(False)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(30, 30, 111, 31))
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 87 italic 24pt \"Segoe UI Black\";")
        self.label_3.setObjectName("label_3")
        VirtualAssistance.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(VirtualAssistance)
        self.statusbar.setObjectName("statusbar")
        VirtualAssistance.setStatusBar(self.statusbar)

        self.retranslateUi(VirtualAssistance)
        QtCore.QMetaObject.connectSlotsByName(VirtualAssistance)

    def retranslateUi(self, VirtualAssistance):
        _translate = QtCore.QCoreApplication.translate
        VirtualAssistance.setWindowTitle(_translate("VirtualAssistance", "MainWindow"))
        self.pushButton.setText(_translate("VirtualAssistance", "Run"))
        self.pushButton_2.setText(_translate("VirtualAssistance", "Exit"))
        self.label_3.setText(_translate("VirtualAssistance", "PRISA"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    VirtualAssistance = QtWidgets.QMainWindow()
    ui = Ui_VirtualAssistance()
    ui.setupUi(VirtualAssistance)
    VirtualAssistance.show()
    sys.exit(app.exec_())
